version: "3"

services:
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
    # restart: always
    container_name: mongodb
    volumes:
      - data-node:/data/db
    ports:
      - 27017:27017
    # logging:
    #   driver: none
 
volumes:
  data-node: